#! /usr/pkg/bin/perl -w
#! /usr/pkg/bin/curl

use strict;
use warnings;
use LWP::Simple;


#my @appnames = ("facebook-browser-for-iphone", "tweetie-2");

my @appnames = ("twitterrific-for-ipad"
,"tweetie-2"
,"twitterfon"
,"twitterfon-pro"
,"twittelator"
,"twittelator-pro"
,"twittelator-pad"
,"fastweet"
,"fastweet-2k"
,"twinkle"
,"twinkle-premium"
,"itweets"
,"retweet"
,"twitfire"
,"twittervision"
,"summizer-realtime-twitter-search"
,"summizer-free-realtime-twitter-search"
,"twitter-trend"
,"simpletweettwitter-client"
,"simplytweet-3"
,"simplytweet-3-free-twitter-client"
,"natsuliphone"
,"quicktweet"
,"tweet-quick"
,"justupdate"
,"oak"
,"hootsuite"
,"tweeterena-2-for-ipad"
,"tweeterena-2-twitter-client"
,"tweetery-twitter-made-easy"
,"twitter-pro"
,"twit-pro-for-ipad"
,"itwitter"
,"twitter-2"
,"twitbird-23-for-twitter"
,"brizzly-for-twitter"
,"twitbit"
,"twitbit-lite"
,"tweetfooter"
,"osfoora"
,"osfoora-hd-for-twitter"
,"tweetdeck"
,"tweetdeck-for-ipad"
,"fluttr-for-twitter"
,"tweetion-2-for-iphone-4-and-ipod-touch-ios-4"
,"tweetion-2-for-iphone-3g-3gs-and-ipod-touch-iphone-os-313"
,"tweetion-2-for-ipad-only"
,"twittervision"
,"sneakytweet"
,"tvvitterbug"
,"tweetings"
,"tweetings-lite"
,"tweetings-for-ipad"
,"tweettime"
,"tweettime-lite-twitter-client"
,"tweettime-for-ipad-twitter-client"
,"duo"
,"tweetpocket"
,"tweetpocketfree"
,"http://appshopper.com/sports/twootball"
,"titema"
,"titema-lite-%e2%80%94-smart-twitter-client"
,"http://appshopper.com/utilities/cafewill-tweet-search-lite"
,"photo-tweet-le"
,"tweet-media"
,"tweet-push-push-notifications-for-twitter"
,"tweet-tuwoo"
,"gossip-one-tweet-at-a-time"
,"tweet"
,"tweet-quick"
,"photo-tweet"
,"photo-tweet-le"
,"gps-tweet"
,"tweet-my-pasteboard"
,"tweet-media-lite"
,"http://appshopper.com/entertainment/tweet-your-poop"
,"http://appshopper.com/entertainment/twitter-tweet-bird-calls"
,"tweet-speak"
,"tweet-that-tune"
,"tweet-tuwoo"
,"how-to-tweet"
,"tweet-sms"
,"http://appshopper.com/music/podtweet"
,"tweet-trends"
,"a-tweet-view"
,"http://appshopper.com/entertainment/filter-tweet"
,"tweet-now"
,"http://appshopper.com/healthcare-fitness/tweet-what-you-eat"
,"http://appshopper.com/games/tweet-defense"
,"http://appshopper.com/news/tweet-glance"
,"yes-no-tweet"
,"tweet-now-2"
,"tweet-song"
,"otg-tweet"
,"tweet-a-tweet"
,"kwik-e-tweet-world-edition"
,"tweet-trends-build-this-app-yourself"
,"tweet-feed"
,"http://appshopper.com/entertainment/lil-tweet"
,"my-quick-tweet"
,"tweet-life-counter-for-iphone"
,"tweet-blast"
,"http://appshopper.com/games/tweet-in-line"
,"tweet-image-slide-touch"
,"sweet-tweet"
,"tweet-only-2"
,"tweet-tweet"
,"http://appshopper.com/healthcare-fitness/tweet-runners"
,"twitter-360"
,"snapntweet"
,"tweet-that-weather"
,"tweet-flow"
,"tweet-mapper"
,"http://appshopper.com/lifestyle/my-tweet-frame"
,"http://appshopper.com/lifestyle/my-tweet-frame"
,"http://appshopper.com/sports/nfl-pro-tweets"
,"http://appshopper.com/sports/jets-tweets"
,"http://appshopper.com/sports/skate-tweets"
,"http://appshopper.com/sports/surf-tweets"
,"tweet-push-push-notifications-for-twitter"
,"itwines"
,"lipex"
,"itwines-hd"
,"a-photo-tweeter"
,"star-tweeter"
,"http://appshopper.com/navigation/twitdar"
,"http://appshopper.com/navigation/twitdarlite-location-auto-tweeter"
,"locati-tweeter"
,"a-photo-tweeter-no-ads"
,"tweetvana"
,"http://appshopper.com/games/tweet-hunter-2"
,"http://appshopper.com/games/tweethunterarena"
,"http://appshopper.com/games/tweet-hunter-lite"
,"doodle-tweet"
,"friend-trend"
,"simplytweet-3-free-twitter-client"
,"latwit"
,"tweepshoot"
,"statustic");

open (MYFILE, '>>links.txt');

foreach my $appname (@appnames){

    my $url = "http://expandurl.com/api/v1/?url=http://appshopper.com/link/$appname";
    my $content = get($url);
    die "could not get" unless defined $content;
    my $match = $content;
    print MYFILE $match . "\n";
}
 
close(MYFILE);

